%% Wrapper for tripleT data

data_dir = 'C:\Users\Aurif\Documents\Work\AJ_SP_RSCINACTIVATION\AllData';
current_dir = cd(data_dir);
file_info = dir('*Events*');
file_list = char({file_info.name});
RecNum = str2num(file_list(:,4:5));
RatNum = (file_list(:,7:9));
RecCondition = (file_list(:,11:13));
NumPaths = str2num(file_list(:,15));
RotationCondition = (file_list(:,17:19));




for filenum = 1:size(file_list,1)                                          %For every rmaps file
    load(file_list(filenum,:))                                             %load it
	ID.Rat{filenum} = RatNum(filenum,:);
	ID.Rec(filenum) = RecNum(filenum,:);   
	ID.Condition{filenum} = RecCondition(filenum,:); 
	ID.NumPaths(filenum) = NumPaths(filenum);
	ID.Rotation{filenum} = RotationCondition(filenum,:);

	[Behavior.Runtimes{filenum}, ...
	Behavior.Timestamps{filenum},...
    Behavior.Velocity{filenum},...
    Behavior.HD{filenum},...
    Behavior.All{filenum},...
    Behavior.Runs{filenum},...
    Behavior.Blocks{filenum},...
    Performance.ErrorBlocks{filenum},...
    Performance.RewardBlocks{filenum},...
    Performance.ErrorRoute{filenum},...
    Performance.MeanErrors(filenum),...
    Performance.PerfectPercent(filenum),...
    BehaviorSeq.Runticker_All{filenum},...
    BehaviorSeq.Runticker_Internals{filenum},...
    BehaviorSeq.Route1Prob{filenum},...
    BehaviorSeq.TransMatrix1{filenum},...
    BehaviorSeq.TransMatrix2{filenum},...
    BehaviorSeq.TransMatrixAll1{filenum},...
    BehaviorSeq.TransMatrixAll2{filenum},...
    TurnAnalysis.IsRightTurn_IntOnly{filenum},...
    TurnAnalysis.PAlt_Turn1(filenum),...
    TurnAnalysis.PAlt_Turn2Any(filenum),...
    TurnAnalysis.PAlt_Turn3Any(filenum),...
    TurnAnalysis.PAlt_Turn2Specific(filenum),...
    TurnAnalysis.PAlt_Turn3Specific(filenum),...
    TurnAnalysis.TotalRTurns(filenum),...
    TurnAnalysis.TotalLTurns(filenum),...
    Returns.PShortReturn(filenum),...
    Returns.PLongReturn(filenum),...
    Returns.PReturnSameSideNext(filenum),...
    Returns.PReturnOppSideNext(filenum),...
    Performance.PerfectBlocks{filenum},...
    Performance.PerfectBlockPermuationCounter{filenum}] = MakeBehavioralStats_wrapped(NumPaths(filenum),indRecStruct);
    
    filenum;
end




