
    FourPind=find(ID.NumPaths ==4)
    EightgtPind=find(ID.NumPaths ==8)

for i = 1: length(P_RightTurn) 

    MaxPerfectPerm(i) = max(Performance.PerfectBlockPermuationCounter{i})
    MaxPerfectPermP(i) = (max(Performance.PerfectBlockPermuationCounter{i}))/(sum(Performance.PerfectBlockPermuationCounter{i}))
end

    figure()
    subplot(3,1,1)
    histogram(P_RightTurn(1,EightgtPind),'binWidth',0.025)
    xlim([0 1])
    hold on
    histogram(P_RightTurn(2,EightgtPind),'binWidth',0.025)
    histogram(P_RightTurn(3,EightgtPind),'binWidth',0.025)
    subplot(3,1,2)
    histogram(P_FirstDegAlt(1,EightgtPind),'binWidth',0.025)
    xlim([0 1])
    hold on
    histogram(P_FirstDegAlt(2,EightgtPind),'binWidth',0.025)
    histogram(P_FirstDegAlt(3,EightgtPind),'binWidth',0.025)
    subplot(3,1,3)
    histogram(P_SecondDegAlt(1,EightgtPind),'binWidth',0.025)
    xlim([0 1])
    hold on
    histogram(P_SecondDegAlt(2,EightgtPind),'binWidth',0.025)
    histogram(P_SecondDegAlt(3,EightgtPind),'binWidth',0.025)

    figure()
    subplot(3,1,1)
    histogram(P_RightTurn(1,FourPind),'binWidth',0.025)
    xlim([0 1])
    hold on
    histogram(P_RightTurn(2,FourPind),'binWidth',0.025)
    histogram(P_RightTurn(3,FourPind),'binWidth',0.025)
    subplot(3,1,2)
    histogram(P_FirstDegAlt(1,FourPind),'binWidth',0.025)
    xlim([0 1])
    hold on
    histogram(P_FirstDegAlt(2,FourPind),'binWidth',0.025)
    histogram(P_FirstDegAlt(3,FourPind),'binWidth',0.025)
    subplot(3,1,3)
    histogram(P_SecondDegAlt(1,FourPind),'binWidth',0.025)
    xlim([0 1])
    hold on
    histogram(P_SecondDegAlt(2,FourPind),'binWidth',0.025)
    histogram(P_SecondDegAlt(3,FourPind),'binWidth',0.025)

    %%


figure()
subplot(3,2,1)
scatter(P_RightTurn(1,EightgtPind), Returns.PShortReturn(EightgtPind))
title("v P(Short Return)")
xlim([0 1])
xlabel("P(RightTurn)")
ylim([0 1])
hold on
scatter(P_RightTurn(2,EightgtPind), Returns.PShortReturn(EightgtPind))
scatter(P_RightTurn(3,EightgtPind), Returns.PShortReturn(EightgtPind))
subplot(3,2,2)
scatter(P_RightTurn(1,EightgtPind), Returns.PReturnOppSideNext(EightgtPind))
title("v P(Return Opposite Side as Next Choice)")
xlim([0 1])
ylim([0 1])
hold on
scatter(P_RightTurn(2,EightgtPind), Returns.PReturnOppSideNext(EightgtPind))
scatter(P_RightTurn(3,EightgtPind), Returns.PReturnOppSideNext(EightgtPind))
subplot(3,2,3)
scatter(P_FirstDegAlt(1,EightgtPind), Returns.PShortReturn(EightgtPind))
xlabel("P(Alternation 1st)")
xlim([0 1])
ylim([0 1])
hold on
scatter(P_FirstDegAlt(2,EightgtPind), Returns.PShortReturn(EightgtPind))
scatter(P_FirstDegAlt(3,EightgtPind), Returns.PShortReturn(EightgtPind))
subplot(3,2,4)
scatter(P_FirstDegAlt(1,EightgtPind), Returns.PReturnOppSideNext(EightgtPind))
xlim([0 1])
ylim([0 1])
hold on
scatter(P_FirstDegAlt(2,EightgtPind), Returns.PReturnOppSideNext(EightgtPind))
scatter(P_FirstDegAlt(3,EightgtPind), Returns.PReturnOppSideNext(EightgtPind))
subplot(3,2,5)
scatter(P_SecondDegAlt(1,EightgtPind), Returns.PShortReturn(EightgtPind))
xlabel("P(Alternation 2nd)")
xlim([0 1])
ylim([0 1])
hold on
scatter(P_SecondDegAlt(2,EightgtPind), Returns.PShortReturn(EightgtPind))
scatter(P_SecondDegAlt(3,EightgtPind), Returns.PShortReturn(EightgtPind))
subplot(3,2,6)
scatter(P_SecondDegAlt(1,EightgtPind), Returns.PReturnOppSideNext(EightgtPind))
xlim([0 1])
ylim([0 1])
hold on
scatter(P_SecondDegAlt(2,EightgtPind), Returns.PReturnOppSideNext(EightgtPind))
scatter(P_SecondDegAlt(3,EightgtPind), Returns.PReturnOppSideNext(EightgtPind))

%% 

figure()
subplot(3,2,1)
scatter(P_RightTurn(1,EightgtPind), Performance.MeanErrors(EightgtPind))
title("v Mean(Errors/Block)")
xlim([0 1])
xlabel("P(RightTurn)")
ylim([0 10])
hold on
scatter(P_RightTurn(2,EightgtPind), Performance.MeanErrors(EightgtPind))
scatter(P_RightTurn(3,EightgtPind), Performance.MeanErrors(EightgtPind))
subplot(3,2,2)
scatter(P_RightTurn(1,EightgtPind), Performance.PerfectPercent(EightgtPind))
title("v P(PerfectBlock)")
xlim([0 1])
ylim([0 1])
hold on
scatter(P_RightTurn(2,EightgtPind), Performance.PerfectPercent(EightgtPind))
scatter(P_RightTurn(3,EightgtPind), Performance.PerfectPercent(EightgtPind))
subplot(3,2,3)
scatter(P_FirstDegAlt(1,EightgtPind), Performance.MeanErrors(EightgtPind))
xlabel("P(Alternation 1st)")
xlim([0 1])
ylim([0 10])
hold on
scatter(P_FirstDegAlt(2,EightgtPind), Performance.MeanErrors(EightgtPind))
scatter(P_FirstDegAlt(3,EightgtPind), Performance.MeanErrors(EightgtPind))
subplot(3,2,4)
scatter(P_FirstDegAlt(1,EightgtPind), Performance.PerfectPercent(EightgtPind))
xlim([0 1])
ylim([0 1])
hold on
scatter(P_FirstDegAlt(2,EightgtPind), Performance.PerfectPercent(EightgtPind))
scatter(P_FirstDegAlt(3,EightgtPind), Performance.PerfectPercent(EightgtPind))
subplot(3,2,5)
scatter(P_SecondDegAlt(1,EightgtPind), Performance.MeanErrors(EightgtPind))
xlabel("P(Alternation 2nd)")
xlim([0 1])
ylim([0 10])
hold on
scatter(P_SecondDegAlt(2,EightgtPind), Performance.MeanErrors(EightgtPind))
scatter(P_SecondDegAlt(3,EightgtPind), Performance.MeanErrors(EightgtPind))
subplot(3,2,6)
scatter(P_SecondDegAlt(1,EightgtPind), Performance.PerfectPercent(EightgtPind))
xlim([0 1])
ylim([0 1])
hold on
scatter(P_SecondDegAlt(2,EightgtPind), Performance.PerfectPercent(EightgtPind))
scatter(P_SecondDegAlt(3,EightgtPind), Performance.PerfectPercent(EightgtPind))
%%


figure()
subplot(3,2,1)
scatter(P_RightTurn(1,FourPind), Returns.PShortReturn(FourPind))
title("v P(Short Return)")
xlim([0 1])
xlabel("P(RightTurn)")
ylim([0 1])
hold on
scatter(P_RightTurn(2,FourPind), Returns.PShortReturn(FourPind))
scatter(P_RightTurn(3,FourPind), Returns.PShortReturn(FourPind))
subplot(3,2,2)
scatter(P_RightTurn(1,FourPind), Returns.PReturnOppSideNext(FourPind))
title("v P(Return Opposite Side as Next Choice)")
xlim([0 1])
ylim([0 1])
hold on
scatter(P_RightTurn(2,FourPind), Returns.PReturnOppSideNext(FourPind))
scatter(P_RightTurn(3,FourPind), Returns.PReturnOppSideNext(FourPind))
subplot(3,2,3)
scatter(P_FirstDegAlt(1,FourPind), Returns.PShortReturn(FourPind))
xlabel("P(Alternation 1st)")
xlim([0 1])
ylim([0 1])
hold on
scatter(P_FirstDegAlt(2,FourPind), Returns.PShortReturn(FourPind))
scatter(P_FirstDegAlt(3,FourPind), Returns.PShortReturn(FourPind))
subplot(3,2,4)
scatter(P_FirstDegAlt(1,FourPind), Returns.PReturnOppSideNext(FourPind))
xlim([0 1])
ylim([0 1])
hold on
scatter(P_FirstDegAlt(2,FourPind), Returns.PReturnOppSideNext(FourPind))
scatter(P_FirstDegAlt(3,FourPind), Returns.PReturnOppSideNext(FourPind))
subplot(3,2,5)
scatter(P_SecondDegAlt(1,FourPind), Returns.PShortReturn(FourPind))
xlabel("P(Alternation 2nd)")
xlim([0 1])
ylim([0 1])
hold on
scatter(P_SecondDegAlt(2,FourPind), Returns.PShortReturn(FourPind))
scatter(P_SecondDegAlt(3,FourPind), Returns.PShortReturn(FourPind))
subplot(3,2,6)
scatter(P_SecondDegAlt(1,FourPind), Returns.PReturnOppSideNext(FourPind))
xlim([0 1])
ylim([0 1])
hold on
scatter(P_SecondDegAlt(2,FourPind), Returns.PReturnOppSideNext(FourPind))
scatter(P_SecondDegAlt(3,FourPind), Returns.PReturnOppSideNext(FourPind))

%% 

figure()
subplot(3,2,1)
scatter(P_RightTurn(1,FourPind), Performance.MeanErrors(FourPind))
title("v Mean(Errors/Block)")
xlim([0 1])
xlabel("P(RightTurn)")
ylim([0 10])
hold on
scatter(P_RightTurn(2,FourPind), Performance.MeanErrors(FourPind))
scatter(P_RightTurn(3,FourPind), Performance.MeanErrors(FourPind))
subplot(3,2,2)
scatter(P_RightTurn(1,FourPind), Performance.PerfectPercent(FourPind))
title("v P(PerfectBlock)")
xlim([0 1])
ylim([0 1])
hold on
scatter(P_RightTurn(2,FourPind), Performance.PerfectPercent(FourPind))
scatter(P_RightTurn(3,FourPind), Performance.PerfectPercent(FourPind))
subplot(3,2,3)
scatter(P_FirstDegAlt(1,FourPind), Performance.MeanErrors(FourPind))
xlabel("P(Alternation 1st)")
xlim([0 1])
ylim([0 10])
hold on
scatter(P_FirstDegAlt(2,FourPind), Performance.MeanErrors(FourPind))
scatter(P_FirstDegAlt(3,FourPind), Performance.MeanErrors(FourPind))
subplot(3,2,4)
scatter(P_FirstDegAlt(1,FourPind), Performance.PerfectPercent(FourPind))
xlim([0 1])
ylim([0 1])
hold on
scatter(P_FirstDegAlt(2,FourPind), Performance.PerfectPercent(FourPind))
scatter(P_FirstDegAlt(3,FourPind), Performance.PerfectPercent(FourPind))
subplot(3,2,5)
scatter(P_SecondDegAlt(1,FourPind), Performance.MeanErrors(FourPind))
xlabel("P(Alternation 2nd)")
xlim([0 1])
ylim([0 10])
hold on
scatter(P_SecondDegAlt(2,FourPind), Performance.MeanErrors(FourPind))
scatter(P_SecondDegAlt(3,FourPind), Performance.MeanErrors(FourPind))
subplot(3,2,6)
scatter(P_SecondDegAlt(1,FourPind), Performance.PerfectPercent(FourPind))
xlim([0 1])
ylim([0 1])
hold on
scatter(P_SecondDegAlt(2,FourPind), Performance.PerfectPercent(FourPind))
scatter(P_SecondDegAlt(3,FourPind), Performance.PerfectPercent(FourPind))

%%

figure()
subplot(3,2,1)
scatter(P_RightTurn(1,EightgtPind), MeanErrorBlocks(EightgtPind))
title("v Mean(Conseq Error)")
xlim([0 1])
xlabel("P(RightTurn)")
ylim([0 10])
hold on
scatter(P_RightTurn(2,EightgtPind), MeanErrorBlocks(EightgtPind))
scatter(P_RightTurn(3,EightgtPind), MeanErrorBlocks(EightgtPind))
subplot(3,2,2)
scatter(P_RightTurn(1,EightgtPind),MeanRewBlocks(EightgtPind))
title("v Mean(Conseq Rew)")
xlim([0 1])
ylim([0 10])
hold on
scatter(P_RightTurn(2,EightgtPind),MeanRewBlocks(EightgtPind))
scatter(P_RightTurn(3,EightgtPind),MeanRewBlocks(EightgtPind))
subplot(3,2,3)
scatter(P_FirstDegAlt(1,EightgtPind), MeanErrorBlocks(EightgtPind))
xlabel("P(Alternation 1st)")
xlim([0 1])
ylim([0 10])
hold on
scatter(P_FirstDegAlt(2,EightgtPind), MeanErrorBlocks(EightgtPind))
scatter(P_FirstDegAlt(3,EightgtPind), MeanErrorBlocks(EightgtPind))
subplot(3,2,4)
scatter(P_FirstDegAlt(1,EightgtPind),MeanRewBlocks(EightgtPind))
xlim([0 1])
ylim([0 10])
hold on
scatter(P_FirstDegAlt(2,EightgtPind),MeanRewBlocks(EightgtPind))
scatter(P_FirstDegAlt(3,EightgtPind),MeanRewBlocks(EightgtPind))
subplot(3,2,5)
scatter(P_SecondDegAlt(1,EightgtPind), MeanErrorBlocks(EightgtPind))
xlabel("P(Alternation 2nd)")
xlim([0 1])
ylim([0 10])
hold on
scatter(P_SecondDegAlt(2,EightgtPind), MeanErrorBlocks(EightgtPind))
scatter(P_SecondDegAlt(3,EightgtPind), MeanErrorBlocks(EightgtPind))
subplot(3,2,6)
scatter(P_SecondDegAlt(1,EightgtPind),MeanRewBlocks(EightgtPind))
xlim([0 1])
ylim([0 10])
hold on
scatter(P_SecondDegAlt(2,EightgtPind),MeanRewBlocks(EightgtPind))
scatter(P_SecondDegAlt(3,EightgtPind),MeanRewBlocks(EightgtPind))
%%

figure()
subplot(3,2,1)
scatter(P_RightTurn(1,FourPind), MeanErrorBlocks(FourPind))
title("v Mean(Conseq Error)")
xlim([0 1])
xlabel("P(RightTurn)")
ylim([0 10])
hold on
scatter(P_RightTurn(2,FourPind), MeanErrorBlocks(FourPind))
scatter(P_RightTurn(3,FourPind), MeanErrorBlocks(FourPind))
subplot(3,2,2)
scatter(P_RightTurn(1,FourPind),MeanRewBlocks(FourPind))
title("v Mean(Conseq Rew)")
xlim([0 1])
ylim([0 10])
hold on
scatter(P_RightTurn(2,FourPind),MeanRewBlocks(FourPind))
scatter(P_RightTurn(3,FourPind),MeanRewBlocks(FourPind))
subplot(3,2,3)
scatter(P_FirstDegAlt(1,FourPind), MeanErrorBlocks(FourPind))
xlabel("P(Alternation 1st)")
xlim([0 1])
ylim([0 10])
hold on
scatter(P_FirstDegAlt(2,FourPind), MeanErrorBlocks(FourPind))
scatter(P_FirstDegAlt(3,FourPind), MeanErrorBlocks(FourPind))
subplot(3,2,4)
scatter(P_FirstDegAlt(1,FourPind),MeanRewBlocks(FourPind))
xlim([0 1])
ylim([0 10])
hold on
scatter(P_FirstDegAlt(2,FourPind),MeanRewBlocks(FourPind))
scatter(P_FirstDegAlt(3,FourPind),MeanRewBlocks(FourPind))
subplot(3,2,5)
scatter(P_SecondDegAlt(1,FourPind), MeanErrorBlocks(FourPind))
xlabel("P(Alternation 2nd)")
xlim([0 1])
ylim([0 10])
hold on
scatter(P_SecondDegAlt(2,FourPind), MeanErrorBlocks(FourPind))
scatter(P_SecondDegAlt(3,FourPind), MeanErrorBlocks(FourPind))
subplot(3,2,6)
scatter(P_SecondDegAlt(1,FourPind),MeanRewBlocks(FourPind))
xlim([0 1])
ylim([0 10])
hold on
scatter(P_SecondDegAlt(2,FourPind),MeanRewBlocks(FourPind))
scatter(P_SecondDegAlt(3,FourPind),MeanRewBlocks(FourPind))

%%

figure()
subplot(3,2,1)
scatter(P_RightTurn(1,EightgtPind), TurnAnalysis.PAlt_Turn1(EightgtPind))
title("v P(1' Alt@ 1)")
xlim([0 1])
xlabel("P(RightTurn)")
ylim([0 1])
hold on
scatter(P_RightTurn(2,EightgtPind), TurnAnalysis.PAlt_Turn1(EightgtPind))
scatter(P_RightTurn(3,EightgtPind), TurnAnalysis.PAlt_Turn1(EightgtPind))
subplot(3,2,2)
scatter(P_RightTurn(1,EightgtPind),MaxPerfectPermP(EightgtPind))
title("v P(Stereotyped Perfect Block)")
xlim([0 1])
ylim([0 1])
hold on
scatter(P_RightTurn(2,EightgtPind),MaxPerfectPermP(EightgtPind))
scatter(P_RightTurn(3,EightgtPind),MaxPerfectPermP(EightgtPind))
subplot(3,2,3)
scatter(P_FirstDegAlt(1,EightgtPind), TurnAnalysis.PAlt_Turn1(EightgtPind))
xlabel("P(Alternation 1st)")
xlim([0 1])
ylim([0 1])
hold on
scatter(P_FirstDegAlt(2,EightgtPind), TurnAnalysis.PAlt_Turn1(EightgtPind))
scatter(P_FirstDegAlt(3,EightgtPind), TurnAnalysis.PAlt_Turn1(EightgtPind))
subplot(3,2,4)
scatter(P_FirstDegAlt(1,EightgtPind),MaxPerfectPermP(EightgtPind))
xlim([0 1])
ylim([0 1])
hold on
scatter(P_FirstDegAlt(2,EightgtPind),MaxPerfectPermP(EightgtPind))
scatter(P_FirstDegAlt(3,EightgtPind),MaxPerfectPermP(EightgtPind))
subplot(3,2,5)
scatter(P_SecondDegAlt(1,EightgtPind), TurnAnalysis.PAlt_Turn1(EightgtPind))
xlabel("P(Alternation 2nd)")
xlim([0 1])
ylim([0 1])
hold on
scatter(P_SecondDegAlt(2,EightgtPind), TurnAnalysis.PAlt_Turn1(EightgtPind))
scatter(P_SecondDegAlt(3,EightgtPind), TurnAnalysis.PAlt_Turn1(EightgtPind))
subplot(3,2,6)
scatter(P_SecondDegAlt(1,EightgtPind),MaxPerfectPermP(EightgtPind))
xlim([0 1])
ylim([0 1])
hold on
scatter(P_SecondDegAlt(2,EightgtPind),MaxPerfectPermP(EightgtPind))
scatter(P_SecondDegAlt(3,EightgtPind),MaxPerfectPermP(EightgtPind))
%%

figure()
subplot(3,2,1)
scatter(P_RightTurn(1,FourPind), TurnAnalysis.PAlt_Turn1(FourPind))
title("v P(1' Alt@ 1)")
xlim([0 1])
xlabel("P(RightTurn)")
ylim([0 1])
hold on
scatter(P_RightTurn(2,FourPind), TurnAnalysis.PAlt_Turn1(FourPind))
scatter(P_RightTurn(3,FourPind), TurnAnalysis.PAlt_Turn1(FourPind))
subplot(3,2,2)
scatter(P_RightTurn(1,FourPind),MaxPerfectPermP(FourPind))
title("v P(Stereotyped Perfect Block)")
xlim([0 1])
ylim([0 1])
hold on
scatter(P_RightTurn(2,FourPind),MaxPerfectPermP(FourPind))
scatter(P_RightTurn(3,FourPind),MaxPerfectPermP(FourPind))
subplot(3,2,3)
scatter(P_FirstDegAlt(1,FourPind), TurnAnalysis.PAlt_Turn1(FourPind))
xlabel("P(Alternation 1st)")
xlim([0 1])
ylim([0 1])
hold on
scatter(P_FirstDegAlt(2,FourPind), TurnAnalysis.PAlt_Turn1(FourPind))
scatter(P_FirstDegAlt(3,FourPind), TurnAnalysis.PAlt_Turn1(FourPind))
subplot(3,2,4)
scatter(P_FirstDegAlt(1,FourPind),MaxPerfectPermP(FourPind))
xlim([0 1])
ylim([0 1])
hold on
scatter(P_FirstDegAlt(2,FourPind),MaxPerfectPermP(FourPind))
scatter(P_FirstDegAlt(3,FourPind),MaxPerfectPermP(FourPind))
subplot(3,2,5)
scatter(P_SecondDegAlt(1,FourPind), TurnAnalysis.PAlt_Turn1(FourPind))
xlabel("P(Alternation 2nd)")
xlim([0 1])
ylim([0 1])
hold on
scatter(P_SecondDegAlt(2,FourPind), TurnAnalysis.PAlt_Turn1(FourPind))
scatter(P_SecondDegAlt(3,FourPind), TurnAnalysis.PAlt_Turn1(FourPind))
subplot(3,2,6)
scatter(P_SecondDegAlt(1,FourPind),MaxPerfectPermP(FourPind))
xlim([0 1])
ylim([0 1])
hold on
scatter(P_SecondDegAlt(2,FourPind),MaxPerfectPermP(FourPind))
scatter(P_SecondDegAlt(3,FourPind),MaxPerfectPermP(FourPind))
